# Generated by Django 5.1.7 on 2025-04-24 16:27

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sr', models.ManyToManyField(related_name='fr', to='merdas.sr')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('fr', models.ManyToManyField(related_name='standards', to='merdas.fr')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=2048)),
                ('question_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.fr')),
                ('sr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.sr')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.standard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('facility_name', models.CharField(max_length=255)),
                ('site_or_province_or_region', models.CharField(max_length=255)),
                ('city_or_site_name', models.CharField(max_length=255)),
                ('asset_gross_value', models.CharField(max_length=255)),
                ('expected_effort', models.CharField(max_length=255)),
                ('business_unit_or_agency', models.CharField(max_length=255)),
                ('facilitator', models.CharField(max_length=255)),
                ('critical_service_name', models.TextField(blank=True, null=True)),
                ('overall_sal', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('confidentiality', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('integrity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('availability', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('contacts', models.ManyToManyField(related_name='assessments_cantacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('critical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_critical', to=settings.AUTH_USER_MODEL)),
                ('org_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_contact', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_org', to='accounts.organization')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationtype')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='merdas.standard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'N/A'), ('alternate', 'Alt')], max_length=20)),
                ('substitute_text', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('references', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='merdas.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='merdas.question')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
