# Generated by Django 5.1.7 on 2025-04-03 13:45

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frs', to='merdas.sr')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='merdas.fr')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
