# Generated by Django 5.1.7 on 2025-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
