# Generated by Django 5.1.7 on 2025-04-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0002_standard_description_standard_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='organization_type',
        ),
    ]
