# Generated by Django 5.1.7 on 2025-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0002_sr_fr_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fr',
            name='sr',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='fr',
        ),
        migrations.AddField(
            model_name='fr',
            name='sr',
            field=models.ManyToManyField(related_name='fr', to='merdas.sr'),
        ),
        migrations.AddField(
            model_name='standard',
            name='fr',
            field=models.ManyToManyField(related_name='standards', to='merdas.fr'),
        ),
    ]
