# Generated by Django 5.1.7 on 2025-04-03 16:23

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0003_remove_fr_sr_remove_standard_fr_fr_sr_standard_fr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=2048)),
                ('question_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.standard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
