# Generated by Django 5.1.7 on 2025-05-01 06:12

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0003_remove_assessment_organization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='references',
        ),
        migrations.CreateModel(
            name='AnswerReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='references/%Y/%m/%d')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='merdas.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
