# Generated by Django 5.1.7 on 2025-04-04 09:41

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0004_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('facility_name', models.CharField(max_length=255)),
                ('site_or_province_or_region', models.CharField(max_length=255)),
                ('city_or_site_name', models.CharField(max_length=255)),
                ('asset_gross_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_effort', models.CharField(max_length=255)),
                ('business_unit_or_agency', models.CharField(max_length=255)),
                ('facilitator', models.CharField(max_length=255)),
                ('critical_service_name', models.TextField(blank=True, null=True)),
                ('overall_sal', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('confidentiality', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('integrity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('availability', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('contacts', models.ManyToManyField(related_name='assessments_cantacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('critical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_critical', to=settings.AUTH_USER_MODEL)),
                ('org_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_contact', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_org', to='merdas.organization')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merdas.organizationtype')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='merdas.standard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'N/A'), ('alternate', 'Alt'), ('review', 'Review')], max_length=20)),
                ('substitute_text', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='merdas.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='merdas.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
