# Generated by Django 5.1.7 on 2025-05-02 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0005_alter_assessment_asset_gross_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerreference',
            name='file',
            field=models.FileField(upload_to='files/references/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='availability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='confidentiality',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='assessments_cantacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='integrity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='overall_sal',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20, null=True),
        ),
    ]
