# Generated by Django 5.1.7 on 2025-04-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0005_assessment_assessmentquestionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.fr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.sr'),
            preserve_default=False,
        ),
    ]
