# Generated by Django 5.1.7 on 2025-04-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0006_question_fr_question_sr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sr',
        ),
    ]
