# Generated by Django 5.1.7 on 2025-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0006_alter_answerreference_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='st_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
