# Generated by Django 5.1.7 on 2025-06-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0007_sr_help_text_standard_st_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='merdas.standard'),
        ),
    ]
