# Generated by Django 5.1.7 on 2025-04-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0008_question_fr_question_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.fr'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merdas.sr'),
        ),
    ]
