# Generated by Django 5.1.7 on 2025-04-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0009_alter_question_fr_alter_question_sr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentQuestionResponse',
        ),
    ]
