# Generated by Django 5.1.7 on 2025-04-21 15:44

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0010_delete_assessmentquestionresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'N/A'), ('alternate', 'Alt')], max_length=20)),
                ('substitute_text', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('references', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='merdas.assessment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='merdas.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
