# Generated by Django 5.1.7 on 2025-04-21 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merdas', '0011_questionresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionResponse',
            new_name='Answer',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('assessment', 'question')},
        ),
    ]
