version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: postgresql_dev
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: edc@1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    container_name: redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --save 60 1 --loglevel warning


volumes:
  pg_data_dev:
  redis_data_dev:
