# Generated by Django 5.1.7 on 2025-08-13 17:28

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('it', 'دارایی\u200cهای IT'), ('non_it', 'دارایی\u200cهای غیر IT')], max_length=32)),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean'), ('date', 'Date'), ('choice', 'Choice')], max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTypeAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('it', 'دارایی\u200cهای IT'), ('non_it', 'دارایی\u200cهای غیر IT')], max_length=32)),
                ('is_required', models.BooleanField(default=False)),
                ('is_multi', models.BooleanField(default=False)),
                ('min_count', models.PositiveIntegerField(default=0)),
                ('max_count', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_rules', to='assets.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='assets.attributecategory'),
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assets.attribute')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attribute_choice',
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('value_int', models.BigIntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_str', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'رجیستر شده'), ('unregistered', 'رجیستر نشده')], default='registered', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.asset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.attribute')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='used_in_values', to='assets.attributechoice')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attribute_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges', to='assets.assetattributevalue')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='assets.asset')),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='assets.asset')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='edges', to='assets.relation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['title'], name='assets_asse_title_b99e60_idx'),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(fields=('asset_type', 'attribute'), name='uq_type_attribute'),
        ),
        migrations.AddConstraint(
            model_name='attributechoice',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='uq_attrchoice_attr_value'),
        ),
        migrations.AddIndex(
            model_name='assetattributevalue',
            index=models.Index(fields=['asset', 'attribute'], name='idx_v_asset_attr'),
        ),
        migrations.AddIndex(
            model_name='assetattributevalue',
            index=models.Index(fields=['status'], name='assets_asse_status_0acc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetattributevalue',
            index=models.Index(fields=['value_date'], name='idx_v_date'),
        ),
        migrations.AddIndex(
            model_name='assetattributevalue',
            index=models.Index(fields=['value_int'], name='idx_v_int'),
        ),
        migrations.AddIndex(
            model_name='assetattributevalue',
            index=models.Index(fields=['value_float'], name='idx_v_float'),
        ),
    ]
