# Generated by Django 5.1.7 on 2025-08-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assettypeattribute',
            name='uq_type_attribute',
        ),
        migrations.RemoveField(
            model_name='assettypeattribute',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='assettypeattribute',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_rules', to='assets.asset'),
            preserve_default=False,
        ),
    ]
