# Generated by Django 5.1.7 on 2025-08-23 13:56

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_assettypeattribute_uq_type_attribute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_registered',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('has_header', models.BooleanField(default=True)),
                ('delimiter', models.CharField(default=',', max_length=4)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('headers', models.JSONField(default=list)),
                ('preview_rows', models.JSONField(default=list)),
                ('asset_column', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_lookup_field', models.CharField(default='id', max_length=20)),
                ('attribute_map', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('edited', 'Edited'), ('committed', 'Committed')], default='uploaded', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('row_index', models.PositiveIntegerField()),
                ('asset_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('error', 'Error'), ('warn', 'Warn')], default='error', max_length=8)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.attribute')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='assets.importsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
