# Generated by Django 5.1.7 on 2025-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_is_registered_importsession_importissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsession',
            name='asset_lookup_field',
            field=models.CharField(default='title', max_length=20),
        ),
    ]
