# Generated by Django 5.1.7 on 2025-08-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_importsession_asset_lookup_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributecategory',
            old_name='value',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='attributecategory',
            old_name='key',
            new_name='title_en',
        ),
    ]
