# Generated by Django 5.1.7 on 2025-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_rename_value_attributecategory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetattributevalue',
            name='choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AttributeChoice',
        ),
    ]
