# Generated by Django 5.1.7 on 2025-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetattributevalue_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
