# Generated by Django 5.1.7 on 2025-09-10 11:49

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_attribute_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('code', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_registered', models.BooleanField(db_index=True, default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='assets.asset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assetattributevalue',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.assetunit'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['asset'], name='assets_asse_asset_i_b9ea8d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetunit',
            index=models.Index(fields=['label'], name='assets_asse_label_e288c3_idx'),
        ),
    ]
