# Generated by Django 5.1.7 on 2025-09-10 18:30

import assets.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetunit_assetattributevalue_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=assets.models._empty_list, help_text='لیست برچسب\u200cها', size=None),
        ),
    ]
