# Generated by Django 5.1.7 on 2025-09-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_attribute_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrelation',
            name='source_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='assets.assetunit'),
        ),
        migrations.AlterField(
            model_name='assetrelation',
            name='target_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='assets.assetunit'),
        ),
    ]
