# Generated by Django 5.1.7 on 2025-09-11 08:27

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetrelation_source_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrelation',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetrelation',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
