# Generated by Django 5.1.7 on 2025-09-11 08:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_assetrelation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetattributevalue',
            name='value_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
