# Generated by Django 5.1.7 on 2025-09-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_assetattributevalue_value_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsession',
            name='asset_lookup_field',
        ),
        migrations.AddField(
            model_name='importissue',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetunit'),
        ),
        migrations.AddField(
            model_name='importissue',
            name='unit_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='unit_label_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='delimiter',
            field=models.CharField(default=',', max_length=8),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='state',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('committed', 'Committed')], default='uploaded', max_length=16),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['session', 'row_index'], name='assets_impo_session_e625d1_idx'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['level'], name='assets_impo_level_38428b_idx'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['code'], name='assets_impo_code_1de080_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['state'], name='assets_impo_state_ce6a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['created_at'], name='assets_impo_created_031f22_idx'),
        ),
    ]
