# Generated by Django 5.1.7 on 2025-09-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_importsession_asset_lookup_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsession',
            name='state',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('edited', 'Edited'), ('committed', 'Committed')], default='uploaded', max_length=16),
        ),
    ]
