# Generated by Django 5.1.7 on 2025-09-25 04:55

import assets.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_importsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='multi_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=assets.models._empty_list, size=None),
        ),
        migrations.AddField(
            model_name='attribute',
            name='single_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=assets.models._empty_list, size=None),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='property_type',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean'), ('date', 'Date'), ('choice', 'Choice'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multi Choice')], max_length=20),
        ),
    ]
