# Generated by Django 5.1.7 on 2025-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_attribute_multi_choices_attribute_single_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='multi_choices',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='single_choices',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='property_type',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean'), ('date', 'Date'), ('tags', 'Tags'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multi Choice')], max_length=20),
        ),
    ]
