# Generated by Django 5.1.7 on 2025-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_rename_multi_choices_attribute_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributecategory',
            old_name='title_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attributecategory',
            name='title',
        ),
        migrations.AddField(
            model_name='attributecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
