# Generated by Django 5.1.7 on 2025-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_rename_title_en_attributecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsession',
            name='attribute_map',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
