# Generated by Django 5.1.7 on 2025-03-29 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='success',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='username',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(default='111', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
