# Generated by Django 5.1.7 on 2025-03-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_loginattempt_ip_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
