# Generated by Django 5.1.7 on 2025-03-31 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_description_usergroup_description'),
        ('merdas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merdas.organization'),
        ),
    ]
