# Generated by Django 5.1.7 on 2025-04-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_groups_user_group'),
        ('merdas', '0006_question_fr_question_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='merdas.organization'),
        ),
    ]
