# Generated by Django 5.1.7 on 2025-03-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_organization'),
        ('merdas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='merdas.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merdas.organization'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='roles',
            field=models.ManyToManyField(related_name='groups', to='accounts.role'),
        ),
    ]
