# Generated by Django 5.1.7 on 2025-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
