# Generated by Django 5.1.7 on 2025-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_passwords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
