# Generated by Django 5.1.7 on 2025-03-29 15:06

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('LOGIN', 'ورود به سامانه'), ('LOGOUT', 'خروج از سامانه'), ('CREATE_USER', 'ایجاد کاربر'), ('UPDATE_USER', 'ویرایش کاربر'), ('DELETE_USER', 'حذف کاربر'), ('CREATE_ROLE', 'ایجاد نقش'), ('UPDATE_ROLE', 'ویرایش نقش'), ('DELETE_ROLE', 'حذف نقش'), ('CREATE_GROUP', 'ایجاد گروه'), ('UPDATE_GROUP', 'ویرایش گروه'), ('DELETE_GROUP', 'حذف گروه'), ('USER_LOCKED', 'لاک شدن کاربر'), ('USER_UNLOCKED', 'آنلاک شدن کاربر'), ('UNAUTHORIZED_ACCESS', 'تلاش برای دسترسی غیرمجاز')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
