# Generated by Django 5.1.7 on 2025-04-24 16:27

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('LOGIN', 'ورود به سامانه'), ('LOGOUT', 'خروج از سامانه'), ('CREATE_USER', 'ایجاد کاربر'), ('UPDATE_USER', 'ویرایش کاربر'), ('DELETE_USER', 'حذف کاربر'), ('CREATE_ROLE', 'ایجاد نقش'), ('UPDATE_ROLE', 'ویرایش نقش'), ('DELETE_ROLE', 'حذف نقش'), ('CREATE_GROUP', 'ایجاد گروه'), ('UPDATE_GROUP', 'ویرایش گروه'), ('DELETE_GROUP', 'حذف گروه'), ('USER_LOCKED', 'لاک شدن کاربر'), ('USER_UNLOCKED', 'آنلاک شدن کاربر'), ('PERMISSION_DENIED', 'دسترسی غیرمجاز')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
