# Generated by Django 5.1.7 on 2025-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='metadata',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
