# Generated by Django 5.1.7 on 2025-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'ورود به سامانه'), ('LOGOUT', 'خروج از سامانه'), ('CREATE_USER', 'ایجاد کاربر'), ('UPDATE_USER', 'ویرایش کاربر'), ('DELETE_USER', 'حذف کاربر'), ('CREATE_ROLE', 'ایجاد نقش'), ('UPDATE_ROLE', 'ویرایش نقش'), ('DELETE_ROLE', 'حذف نقش'), ('CREATE_GROUP', 'ایجاد گروه'), ('UPDATE_GROUP', 'ویرایش گروه'), ('DELETE_GROUP', 'حذف گروه'), ('USER_LOCKED', 'لاک شدن کاربر'), ('USER_UNLOCKED', 'آنلاک شدن کاربر'), ('PERMISSION_DENIED', 'دسترسی غیرمجاز')], max_length=50),
        ),
    ]
