# Generated by Django 5.1.7 on 2025-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
